Decoded TESObjectCell further
Starfield-Reverse-Engineering/CommonLibSF pull request #47
Opened 2023-09-14 16:00 UTC by TommInfinite

2023-09-14 17:08 UTC, ThirdEyeSqueegee commented
Please fix the build errors and ensure that the PR name follows the conventional commits pattern (see other PRs for examples)

2023-09-14 17:12 UTC, ThirdEyeSqueegee requested changes
Please fix the build errors and ensure that the PR name follows the conventional commits pattern (see other PRs for examples)

2023-09-14 19:17 UTC, Qudix commented
New headers need to be added to `RE/Starfield.h` in alphabetical order

2023-09-14 19:34 UTC, ThirdEyeSqueegee commented
> New headers need to be added to `RE/Starfield.h` in alphabetical order

There's a script that adds them automatically during build configuration

2023-09-15 01:39 UTC, gottyduke commented on CommonLibSF/include/RE/T/TESObjectCELL.h
> +    	UInt16					flags;				// 48
Use `std::uint16_t` in CommonLib. `UInt16` is undefined

2023-09-15 07:01 UTC, closed without merging